name: "Terraform"

on:
  pull_request_target:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
      AWS_VPC_ID: ${{ secrets.AWS_VPC_ID }}
      AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
      AWS_INSTANCE_TYPE: ${{ secrets.AWS_INSTANCE_TYPE }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Check if PR is from a Fork
        id: check-fork
        run: |
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.event.pull_request.base.repo.full_name }}" ]]; then
            echo "This PR is not from a forked repository. Skipping the workflow."
            echo "IS_FORK=false" >> $GITHUB_ENV
            exit 0
          else
            echo "This PR is from a forked repository. Continuing the workflow."
            echo "IS_FORK=true" >> $GITHUB_ENV
          fi

      - name: Checkout Forked Repo
        if: env.IS_FORK == 'true'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch PR Details
        if: env.IS_FORK == 'true'
        id: pr-details
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        if: env.IS_FORK == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Set Up SSH Key
        if: env.IS_FORK == 'true'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/terraform
          chmod 600 ~/.ssh/terraform
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Terraform Workflow
        if: env.IS_FORK == 'true'
        run: |
          make init
          make validate
          make plan
          make apply
          make verify || echo "VERIFY_FAILED=true" >> $GITHUB_ENV

      - name: Send Slack Notification
        if: env.IS_FORK == 'true'
        run: |
          if [ "${VERIFY_FAILED}" = "true" ]; then
            ./slack_notify.sh "${{ secrets.SLACK_WEBHOOK_URL }}" "deploy-failed" "Terraform Deployment" "${{ env.PR_AUTHOR }}" "PR #${{ env.PR_NUMBER }}"
          else
            ./slack_notify.sh "${{ secrets.SLACK_WEBHOOK_URL }}" "success" "Terraform Deployment" "${{ env.PR_AUTHOR }}" "PR #${{ env.PR_NUMBER }}"
          fi