name: "Terraform"

on:
  pull_request_target:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
      AWS_VPC_ID: ${{ secrets.AWS_VPC_ID }}
      AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
      AWS_INSTANCE_TYPE: ${{ secrets.AWS_INSTANCE_TYPE }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    steps:
      - name: Checkout Forked Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Set Environment Variables
        run: |
          echo "AWS_REGION=${{ env.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_KEY_NAME=${{ env.AWS_KEY_NAME }}" >> $GITHUB_ENV
          echo "AWS_VPC_ID=${{ env.AWS_VPC_ID }}" >> $GITHUB_ENV
          echo "AWS_SUBNET_ID=${{ env.AWS_SUBNET_ID }}" >> $GITHUB_ENV
          echo "AWS_INSTANCE_TYPE=${{ env.AWS_INSTANCE_TYPE }}" >> $GITHUB_ENV
      
      - name: Terraform Workflow
        run: |
          make init
          make validate
          make plan
          make apply
          make verify