name: "Terraform"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Validation"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Check if PR is from a Fork
        id: check-fork
        run: |
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.event.pull_request.base.repo.full_name }}" ]]; then
            echo "This PR is not from a forked repository. Skipping the workflow."
            echo "IS_FORK=false" >> $GITHUB_ENV
            exit 0
          else
            echo "This PR is from a forked repository. Continuing the workflow."
            echo "IS_FORK=true" >> $GITHUB_ENV
          fi

      - name: Checkout Forked Repo
        if: env.IS_FORK == 'true'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Determine Assignment Directory
        if: env.IS_FORK == 'true'
        id: assignment-dir
        run: |
          ASSIGNMENT_DIR=$(find assignments/public-cloud/aws -type d -name "*")
          echo "ASSIGNMENT_DIR=${ASSIGNMENT_DIR}" >> $GITHUB_ENV
          echo "Assignment directory: $ASSIGNMENT_DIR"

      - name: Configure AWS Credentials
        if: env.IS_FORK == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set Up SSH Key
        if: env.IS_FORK == 'true'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/terraform
          chmod 600 ~/.ssh/terraform
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Terraform Workflow
        if: env.IS_FORK == 'true'
        working-directory: ${{ env.ASSIGNMENT_DIR }}
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan || echo "VERIFY_FAILED=true" >> $GITHUB_ENV

      - name: Send Slack Notification
        if: env.IS_FORK == 'true'
        run: |
          if [ "${VERIFY_FAILED}" = "true" ]; then
            ./slack_notify.sh "${{ secrets.SLACK_WEBHOOK_URL }}" "deploy-failed" "Terraform Deployment" "${{ github.event.pull_request.user.login }}" "PR #${{ github.event.pull_request.number }}"
          else
            ./slack_notify.sh "${{ secrets.SLACK_WEBHOOK_URL }}" "success" "Terraform Deployment" "${{ github.event.pull_request.user.login }}" "PR #${{ github.event.pull_request.number }}"
          fi